sudo: required
services:
- docker
script:
- |
  docker-compose -f docker-compose.tests.yml run unittest &&
  docker-compose build &&
  docker login -u $DOCKER_USER -p $DOCKER_PASSWORD &&
  docker push damonf8086/aglcatsconsumer:${TAG}
env:
  global:
  - TAG=latest
  - secure: PiXI62+akd6If2f/4Iu8O8oI5lWkcRjn5bBgdrLXCH2VJmVkldYop9HKNQE7SuZIr202oXln36EzozcS9Ark34YVVxt8H7gKs9WeRti0CcakV0kdvFVoIvTd4Y2AkeqFeh3IzPHWmYae3Ecn2NWdcgpkGMcZ+RCTVlXJhicdt8K64vB5ZvUTKbYYW+tZ7EJOP2rtDNaz7DjRx1E9Rq83yY7zup4COO+aDu/olBTySWoHWnsqefgXZJk6RsZcW4U6h7I0mi8vL4cwKgKrDzt2ShHdjxCA0dkT3qCGwDWaf+10xeHd6huIAxILsGf3aWuWz14nWCS26S2jWH6IjcCcdZP6j5fQuEtOYGXE4MoFyx1E6nr70sKrlcuDM/CI7qaUy8m8NvRGY2UNU3rz/H9OpNzxK3JBrLsbiQW8whSGqWU4r8RS32E9jlbOy96jIJ5gi7yhDkhw7eMWnoO1ykIKw212RfA2vGz4/FI1DgSo3fZ++ffC8GII2QWydfNPhn+1v4rxWVwNMdUN9VGHVqrVXBX/54NW9L2u3REKIb95bk0tWUJG5XbTvVZ/MEGBXJwcI+J3m/LtUps/1yWQ2sGnyxAPdo2jXbspFhXCPZLYEstDxpaoVBzMXw8vy9YKoyH0xUpnA3fxOZ+LSYGFe9ovHzg+/hu9DoFqodpss731os0=
  - secure: JjU77v+cCfT67gk2W28YyuIlCXqjHdZrBxYPUxwK7Lfo6wWyx1Zv+LnTOcQXqsE1LmsUtJ2Ie12Bez2RRKt5a9Enl6UjzXsiT/YuXW1+q88TyteT5uRRph6Hp26R8tw6T17DNoRafYSbuc3vU7b6nPoDjyN7hbLxR7AnDfdP4521kmbWPkM5ckN2a6Fe3VD6njAj2XNiREePQRrLTblTxPiXbRxxf2Gn7h+UZtWI+HuQRxLfC/te18yuNJulV3qNKSQL4aZzQNj6nCEKJgrEHgQ7DKDTFySCHxuHBXwyywJ75kPMta5Q8ykNSxN/3txCYlpfqLt3u6g7N1BAjKfg4KkVGT4oCVKwAsidjgTSRTOOnVORefOcPXHQnAd3d+XW2jwvkazCI5s2+x7HcOAC1SvdZHHZsHvjgIt8a3nR2iYX95vlb2MWRRTcgpJ+LdIPKK87gtcG5/Zz0zVUYs8gfkIkqfJephqll/sGAR6JzTpy1vT2cY7wYEr89BU3l4sSzVTiSyTI14NsjaKTYC3jiccyv7CBovFZ7QfUBJda0Y2eA8cYvPB7Ptx8yk/bGDuyvK2YchbAdYGdCEXQCUYtHS3dHr4d2/op2gELWIEWHDXJOaSEHvv6EDYYlS/fYg0mEadQuDRCpOthJaADOTCnPtXWX9pJ/Ki8jEm0B4s0NW8=
